services:
  database:
    image: mysql:8
    container_name: adj-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adj-demo
    ports:
      - "3307:3306"
    networks:
      - adj-net
    volumes:
      - adj-volume:/var/lib/mysql

  frontend:
    image: client:v1.0
    build:
      context: ./client
      args:
        API_HOST: localhost
        API_PORT: 8081
        API_BASE: /adj-api
    container_name: adj-client
    ports:
      - "3000:80"
    networks:
      - adj-net
    depends_on:
      - database

  backend:
    image: server:v1.0
    build:
      context: ./server
    environment:
      SERVER_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: adj-demo
      DB_USER: root
      DB_PASS: root
    ports:
      - "8081:8080"
    networks:
      - adj-net
    depends_on:
      - frontend

#crear estas redes docker create bridge
networks:
  adj-net:
    external: true

#docker volume create adj-volume
volumes:
  adj-volume:
    external: true